# fly.toml app configuration file generated for frontend-empty-shadow-574 on 2025-02-22T14:39:36+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-empty-shadow-574'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
