# fly.toml app configuration file generated for backend-wild-firefly-7466 on 2025-02-22T13:47:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-wild-firefly-7466'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
