name: Auto Delete PR Preview
on:
  pull_request:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Read Fly.io App Name
        run: |
          echo "BACKEND_APP_NAME=$(grep -oP '(?<=app = ").*(?=")' backend/fly.toml)" >> $GITHUB_ENV
          echo "FRONTEND_APP_NAME=$(grep -oP '(?<=app = ").*(?=")' frontend/fly.toml)" >> $GITHUB_ENV

      - name: Delete Backend
        run: fly apps destroy ${{ env.BACKEND_APP_NAME }}-pr-${{ github.event.pull_request.number }} --yes

      - name: Delete Frontend
        run: fly apps destroy ${{ env.FRONTEND_APP_NAME }}-pr-${{ github.event.pull_request.number }} --yes

      - name: Delete Database
        run: fly postgres delete ${{ env.BACKEND_APP_NAME }}-db-pr-${{ github.event.pull_request.number }} --yes
