name: Preview App

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_ORG_TOKEN }}
  FLY_REGION: <your region>
  FLY_ORG: <your org>

jobs:
  staging_app:
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Read Fly.io App Name
        run: |
          echo "BACKEND_APP_NAME=$(grep -oP '(?<=app = ").*(?=")' backend/fly.toml)" >> $GITHUB_ENV
          echo "FRONTEND_APP_NAME=$(grep -oP '(?<=app = ").*(?=")' frontend/fly.toml)" >> $GITHUB_ENV

      - name: Deploy backend
        uses: superfly/fly-pr-review-apps@main
        with:
          path: backend
          name: pr-${{ github.event.number }}-${{ env.BACKEND_APP_NAME }}

      - name: Deploy frontend
        uses: superfly/fly-pr-review-apps@main
        with:
          name: pr-${{ github.event.number }}-${{ env.FRONTEND_APP_NAME }}
