name: Deploy PR Preview
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Read Fly.io App Name
        run: |
          echo "BACKEND_APP_NAME=$(grep -oP '(?<=app = ").*(?=")' backend/fly.toml)" >> $GITHUB_ENV
          echo "FRONTEND_APP_NAME=$(grep -oP '(?<=app = ").*(?=")' frontend/fly.toml)" >> $GITHUB_ENV

      - name: Deploy Backend to Fly.io
        working-directory: backend
        run: flyctl deploy --remote-only --app ${{ env.BACKEND_APP_NAME }}-pr-${{ github.event.pull_request.number }}

      - name: Deploy Frontend to Fly.io
        working-directory: frontend
        run: flyctl deploy --remote-only --app ${{ env.FRONTEND_APP_NAME }}-pr-${{ github.event.pull_request.number }}

      - name: Deploy Database
        run: flyctl postgres create --name ${{ env.BACKEND_APP_NAME }}-db-pr-${{ github.event.pull_request.number }} --volume-size=1 --vm-size shared-cpu-1x --region sea
